---
title: "class11"
author: "Sze Sze Chan"
date: "2025-02-19"
output: html_document
---

```{r}
results_dir <- "smoothie_58941/"
```

```{r}
pdb_files <- list.files(path=results_dir,
pattern="*.pdb",
full.names = TRUE)
# Print our PDB file names
basename(pdb_files)
```

```{r}
library(bio3d)
```

```{r}
pdbs <- pdbaln(pdb_files, fit=TRUE, exefile="msa")
```

```{r}
rd <- rmsd(pdbs, fit=T)
range(rd)
```

```{r}
dim(rd)
```

```{r}
library(pheatmap)
colnames(rd) <- paste0("m",1:6)
rownames(rd) <- paste0("m",1:6)
pheatmap(rd)
```

```{r}
pdb <- read.pdb("1hsg")
```

```{r}
plotb3(pdbs$b[1,], typ="l", lwd=2, sse=pdb)
points(pdbs$b[2,], typ="l", col="red")
points(pdbs$b[3,], typ="l", col="blue")
points(pdbs$b[4,], typ="l", col="darkgreen")
points(pdbs$b[5,], typ="l", col="orange")
abline(v=100, col="gray")
```

```{r}
core <- core.find(pdbs)
```

```{r}
core.inds <- print(core, vol=0.5)
```


```{r}
xyz <- pdbfit(pdbs, core.inds, outpath="corefit_structures")
```


```{r}
rf <- rmsf(xyz)
plotb3(rf, sse=pdb)
abline(v=100, col="gray", ylab="RMSF")
```


```{r}
library(jsonlite)

pae_files <- list.files(path=results_dir,
pattern=".*model.*\\.json",
full.names = TRUE)
pae1 <- read_json(pae_files[1],simplifyVector = TRUE)
pae5 <- read_json(pae_files[5],simplifyVector = TRUE)
attributes(pae1)
```

```{r}
# Per-residue pLDDT scores
# same as B-factor of PDB..
head(pae1$plddt)
```

The maximum PAE values are useful for ranking models. Here we can see that model 5 is much worse than model 1. The lower the PAE score the better. How about the other models, what are thir max PAE scores?

```{r}
pae1$max_pae
```

```{r}
pae5$max_pae
```


```{r}
plot.dmat(pae1$pae,
xlab="Residue Position (i)",
ylab="Residue Position (j)")
```


```{r}
plot.dmat(pae5$pae,
xlab="Residue Position (i)",
ylab="Residue Position (j)",
grid.col = "black",
zlim=c(0,30))
```


```{r}
plot.dmat(pae1$pae,
xlab="Residue Position (i)",
ylab="Residue Position (j)",
grid.col = "black",
zlim=c(0,30))
```

```{r}
aln_file <- list.files(path=results_dir,
pattern=".a3m$",
full.names = TRUE)
aln_file
```

```{r}
aln <- read.fasta(aln_file[1], to.upper = TRUE)
```

How many sequences are in this alignment
```{r}
dim(aln$ali)
```

We can score residue conservation in the alignment with the conserv() function.

```{r}
sim <- conserv(aln)
plotb3(sim[1:99], sse=trim.pdb(pdb, chain="A"),
ylab="Conservation Score")
```


```{r}
con <- consensus(aln, cutoff = 0.9)
con$seq
```




















